/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as VelocitaRouteImport } from './routes/velocita'
import { Route as NotteBomberRouteImport } from './routes/notte-bomber'
import { Route as StradaBlousonRouteImport } from './routes/strada-blouson'
import { Route as AlbaShearlingRouteImport } from './routes/alba-shearling'
import { Route as RiposoQuiltedRouteImport } from './routes/riposo-quilted'
import { Route as SeraMotoRouteImport } from './routes/sera-moto'
import { Route as MezzanotteCoatRouteImport } from './routes/mezzanotte-coat'
import { Route as CorsoOvershirtRouteImport } from './routes/corso-overshirt'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport } as any)
const BagRoute = BagRouteImport.update({ id: '/bag', path: '/bag', getParentRoute: () => rootRouteImport } as any)
const CollectionsRoute = CollectionsRouteImport.update({ id: '/collections', path: '/collections', getParentRoute: () => rootRouteImport } as any)
const JournalRoute = JournalRouteImport.update({ id: '/journal', path: '/journal', getParentRoute: () => rootRouteImport } as any)
const VelocitaRoute = VelocitaRouteImport.update({ id: '/velocita', path: '/velocita', getParentRoute: () => rootRouteImport } as any)
const NotteBomberRoute = NotteBomberRouteImport.update({ id: '/notte-bomber', path: '/notte-bomber', getParentRoute: () => rootRouteImport } as any)
const StradaBlousonRoute = StradaBlousonRouteImport.update({ id: '/strada-blouson', path: '/strada-blouson', getParentRoute: () => rootRouteImport } as any)
const AlbaShearlingRoute = AlbaShearlingRouteImport.update({ id: '/alba-shearling', path: '/alba-shearling', getParentRoute: () => rootRouteImport } as any)
const RiposoQuiltedRoute = RiposoQuiltedRouteImport.update({ id: '/riposo-quilted', path: '/riposo-quilted', getParentRoute: () => rootRouteImport } as any)
const SeraMotoRoute = SeraMotoRouteImport.update({ id: '/sera-moto', path: '/sera-moto', getParentRoute: () => rootRouteImport } as any)
const MezzanotteCoatRoute = MezzanotteCoatRouteImport.update({ id: '/mezzanotte-coat', path: '/mezzanotte-coat', getParentRoute: () => rootRouteImport } as any)
const CorsoOvershirtRoute = CorsoOvershirtRouteImport.update({ id: '/corso-overshirt', path: '/corso-overshirt', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bag': typeof BagRoute
  '/collections': typeof CollectionsRoute
  '/journal': typeof JournalRoute
  '/velocita': typeof VelocitaRoute
  '/notte-bomber': typeof NotteBomberRoute
  '/strada-blouson': typeof StradaBlousonRoute
  '/alba-shearling': typeof AlbaShearlingRoute
  '/riposo-quilted': typeof RiposoQuiltedRoute
  '/sera-moto': typeof SeraMotoRoute
  '/mezzanotte-coat': typeof MezzanotteCoatRoute
  '/corso-overshirt': typeof CorsoOvershirtRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bag': typeof BagRoute
  '/collections': typeof CollectionsRoute
  '/journal': typeof JournalRoute
  '/velocita': typeof VelocitaRoute
  '/notte-bomber': typeof NotteBomberRoute
  '/strada-blouson': typeof StradaBlousonRoute
  '/alba-shearling': typeof AlbaShearlingRoute
  '/riposo-quilted': typeof RiposoQuiltedRoute
  '/sera-moto': typeof SeraMotoRoute
  '/mezzanotte-coat': typeof MezzanotteCoatRoute
  '/corso-overshirt': typeof CorsoOvershirtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BagRoute: typeof BagRoute
  CollectionsRoute: typeof CollectionsRoute
  JournalRoute: typeof JournalRoute
  VelocitaRoute: typeof VelocitaRoute
  NotteBomberRoute: typeof NotteBomberRoute
  StradaBlousonRoute: typeof StradaBlousonRoute
  AlbaShearlingRoute: typeof AlbaShearlingRoute
  RiposoQuiltedRoute: typeof RiposoQuiltedRoute
  SeraMotoRoute: typeof SeraMotoRoute
  MezzanotteCoatRoute: typeof MezzanotteCoatRoute
  CorsoOvershirtRoute: typeof CorsoOvershirtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/account': { id: '/account'; path: '/account'; fullPath: '/account'; preLoaderRoute: typeof AccountRouteImport; parentRoute: typeof rootRouteImport }
    '/bag': { id: '/bag'; path: '/bag'; fullPath: '/bag'; preLoaderRoute: typeof BagRouteImport; parentRoute: typeof rootRouteImport }
    '/collections': { id: '/collections'; path: '/collections'; fullPath: '/collections'; preLoaderRoute: typeof CollectionsRouteImport; parentRoute: typeof rootRouteImport }
    '/journal': { id: '/journal'; path: '/journal'; fullPath: '/journal'; preLoaderRoute: typeof JournalRouteImport; parentRoute: typeof rootRouteImport }
    '/velocita': { id: '/velocita'; path: '/velocita'; fullPath: '/velocita'; preLoaderRoute: typeof VelocitaRouteImport; parentRoute: typeof rootRouteImport }
    '/notte-bomber': { id: '/notte-bomber'; path: '/notte-bomber'; fullPath: '/notte-bomber'; preLoaderRoute: typeof NotteBomberRouteImport; parentRoute: typeof rootRouteImport }
    '/strada-blouson': { id: '/strada-blouson'; path: '/strada-blouson'; fullPath: '/strada-blouson'; preLoaderRoute: typeof StradaBlousonRouteImport; parentRoute: typeof rootRouteImport }
    '/alba-shearling': { id: '/alba-shearling'; path: '/alba-shearling'; fullPath: '/alba-shearling'; preLoaderRoute: typeof AlbaShearlingRouteImport; parentRoute: typeof rootRouteImport }
    '/riposo-quilted': { id: '/riposo-quilted'; path: '/riposo-quilted'; fullPath: '/riposo-quilted'; preLoaderRoute: typeof RiposoQuiltedRouteImport; parentRoute: typeof rootRouteImport }
    '/sera-moto': { id: '/sera-moto'; path: '/sera-moto'; fullPath: '/sera-moto'; preLoaderRoute: typeof SeraMotoRouteImport; parentRoute: typeof rootRouteImport }
    '/mezzanotte-coat': { id: '/mezzanotte-coat'; path: '/mezzanotte-coat'; fullPath: '/mezzanotte-coat'; preLoaderRoute: typeof MezzanotteCoatRouteImport; parentRoute: typeof rootRouteImport }
    '/corso-overshirt': { id: '/corso-overshirt'; path: '/corso-overshirt'; fullPath: '/corso-overshirt'; preLoaderRoute: typeof CorsoOvershirtRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AccountRoute,
  BagRoute,
  CollectionsRoute,
  JournalRoute,
  VelocitaRoute,
  NotteBomberRoute,
  StradaBlousonRoute,
  AlbaShearlingRoute,
  RiposoQuiltedRoute,
  SeraMotoRoute,
  MezzanotteCoatRoute,
  CorsoOvershirtRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
